apiVersion: v1
kind: Service

metadata:
    name:   sjsump-api-svc
    # namespace:  sjsump

spec:
    selector:
        app:   sjsump-api
    ports:
        -   port:   80
            name:   sjsump-api-port
    type:   ClusterIP
