apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjsump-api-deployment
  # namespace: sjsump
  labels:
    app: sjsump-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjsump-api
  template:
    metadata:
      labels:
        app: sjsump-api
    spec:
      containers:
      - name: sjsump-api
        image: sjsump-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
